name: Deploy to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Compilar app
        run: dotnet publish -c Release -o ./publish

      - name: Login en AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login en ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag y Push Docker
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/miapi:${{ github.sha }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Instalar kubectl (oficial AWS)
        run: |
          curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-03-12/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin
          kubectl version --client

      - name: Configurar kubeconfig para EKS
        run: |
          aws eks update-kubeconfig --name unique-classical-unicorn --region us-east-1

      - name: Aplicar manifests
        run: |
          sed -i "s|703409456891.dkr.ecr.us-east-1.amazonaws.com/miapi:latest|$IMAGE_URI|" deployment.yaml
          kubectl apply -f deployment.yaml
